### ISSUE TITLE
Project name?

### ISSUE THREAD

**Issue by jrasanen** [CheckoutFinland/aws-secret-storage#2]
@minttu, could the repository be renamed into "aws-secret-storage" to be more descriptive? What do you think?

**Comment by minttu** [comment]
Sounds good. The cli commands start to get a bit long at that point eg. `aws-secret-storage-encrypt`. But I think it's a better name.

**Comment by jrasanen** [comment]
Then it's also nice that aws related projects are organized by `aws-` prefix in development directory listing.

**Comment by jrasanen** [comment]
Thank you!
